name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    env:
      APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      FIREBASE_ACCESS_TOKEN: ${{ secrets.FIREBASE_ACCESS_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH Keys and known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CERTS_REPO_CERT }}" > ~/.ssh/certs_rsa
        chmod 600 ~/.ssh/certs_rsa
        ssh-add ~/.ssh/certs_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Install firebase tool
      run: |
        curl -sL firebase.tools | bash
    - name: Build
      run: |
        fastlane setup
        fastlane build_snapshot
    - name: Deploy to firebase
      if: github.ref == 'refs/heads/master'
      run: |
        fastlane upload_to_firebase
